### PR TITLE
RTK: add CCPA support 

### PR DESCRIPTION
**Pull request by musikele**
## Type of Change

- [ ] New adapter
- [x] Feature Update
- [ ] Bug Fix
- [ ] Code Refactor
- [ ] Other

## Description of Change

Add CCPA support for RTK aardvark bidder.

### CODE REVIEW

**Comment by musikele** [comment]
We have already submitted RTK bidder in the past (https://github.com/indexexchange/ix-library-adapters/pull/71) but for some reason it got reverted (https://github.com/indexexchange/ix-library-adapters/pull/153). 

What happened? 

Also, is canary the right branch to submit?

**Comment by jas-singh** [comment]
Hi @musikele 

That was reverted as we did not get a sign off from your team to have the change promoted to production (master) from a canary release.

**Comment by musikele** [comment]
Hi @jas-singh , thank you for your response. 
So, following the guide at https://kb.indexexchange.com/Adapters/Update_a_Certified_Adapter.htm We now have to accomplish step 2:

> Log an Adapter Update ticket. In our external service desk, log an Adapter Update ticket.
> Need help setting up an account or logging the ticket? To learn more, see External Service Desk for Partners

**Comment by jas-singh** [comment]
Hi @musikele Please email adapter-certifications@indexexchange.com & Khushi.Irani@indexexchange.com and they'll be able to guide you with the next steps

**Pull request merged**
