### PR TITLE
[HTP-68] TripleLift adapter and tmax/CCPA updates

### PR DESCRIPTION
**Pull request by davidwoodsandersen**
## Type of Change

- [ ] New adapter
- [x] Feature Update
- [ ] Bug Fix
- [ ] Code Refactor
- [ ] Other

## Description of Change
- Migrates TripleLift adapter from [here](https://github.com/indexexchange/triple-lift-adapter)
- Adds system tests
- Adds tmax query param to auction request
- Adds CCPA query param to auction request
- Hardcodes HTTPS protocol for auction request

### CODE REVIEW

**Comment by ix-certification** [comment]
Hi!

In the same PR, can you please remove `triple-lift/ `from `.eslintignore`.

Thanks

**Comment by jas-singh** [comment]
hi @davidwoodsandersen 

With the new bid request parameter `tmax`, is the expectation to signal the IX library timeout?

**Comment by davidwoodsandersen** [comment]
@jas-singh Yes, our exchange API will receive that value and set it as the bid request timeout server-side. Is `configs.timeout` the wrong location?

**Comment by jas-singh** [comment]
@davidwoodsandersen  

In that case it should be `SpaceCamp.globalTimeout` instead. This will give you access to the header auction timeout.

**Comment by davidwoodsandersen** [comment]
@jas-singh thanks, this is ready for another look when you get a chance.

**Comment by jas-singh** [comment]
Thanks for update @davidwoodsandersen. We'll be merging it in shortly.

**Comment by ix-certification** [comment]
Hi!

Just so your team is aware, we will be passing an empty string if for whatever reason we are not able to pass back a consent. Reasons such as CCPA times out or the API is down.

Cheers!

**Comment by davidwoodsandersen** [comment]
@ix-certification does this mean in the case of a CCPA problem, the return value of `ComplianceService.usp.getConsent()` with still be truthy?

**Comment by ix-certification** [comment]
@davidwoodsandersen Correct! 
Here is the example of the object it will return `{version: 1, uspString: ""}`.

**Pull request merged**
