### PR TITLE
[HTP-1000] Kargo Adapter: Support Liveramp IDL Envelope and GDPR

### PR DESCRIPTION
**Pull request by wedgeV**
## Type of Change
- [ ] New adapter
- [x] Feature Update
- [ ] Bug Fix
- [ ] Code Refactor
- [x] Other

## Description of Change
Support Liveramp IDL Envelope
Support GDPR

### CODE REVIEW

**Comment by cd0n0van** [comment]
Hi @wedgeV - can you please confirm if you'd like IX to merge this into the Canary or Master branch? If Master, can you please pull and re-open? Otherwise, we will deploy to Canary for your testing.

Thanks!

**Comment by wedgeV** [comment]
@cd0n0van thanks for merging. how do we get this rolled out to pubs asap?

**Comment by wedgeV** [comment]
@cd0n0van sent you an email a few days ago, can you let me know what exactly you need us to do to get this released? re-open this as PR into master?

**Comment by cd0n0van** [comment]
Hi @wedgeV - confirming we've tested this change and will be promoting it from canary to master in our next sprint.

**Comment by transistorize** [comment]
Thank you very much, @cd0n0van !

**Pull request merged**
