### PR TITLE
JustPremium: Add support for ccpa

### PR DESCRIPTION
**Pull request by nwlosinski**
## Type of Change

- [ ] New adapter
- [x] Feature Update
- [ ] Bug Fix
- [ ] Code Refactor
- [ ] Other

## Description of Change

Support for CCPA.

### CODE REVIEW

**Comment by ix-certification** [comment]
Hello, 
We dont see a corresponding JIRA Ticket for this pull request. I wanted to bring this to your attention, since this is filed for CCPA, and might be time sensitive, i wanted to bring this to your attention. Please file a JIRA ticket using our external service desk if you want this work to be prioritized and slotted for review.

**Comment by ix-certification** [comment]
HTP Ticket missing..

**Comment by nwlosinski** [comment]
Thanks for information.  Ticket has just been created (HTP-136).

**Comment by ix-certification** [comment]
Hello, checking in on this pull request. Can you confirm this is still a pending request for IX?

**Comment by nwlosinski** [comment]
Hello, yes this is still a pending request.

**Pull request merged**
