### PR TITLE
Conversant: Move adapter and add ccpa support

### PR DESCRIPTION
**Pull request by pycnvr**
## Type of Change

- [ ] New adapter
- [x] Feature Update
- [ ] Bug Fix
- [ ] Code Refactor
- [ ] Other

## Description of Change
* Move Conversant adapter from old repo
* Add CCPA support
### Related Issue

#

### CODE REVIEW

**Comment by ix-certification** [comment]
Hello, checking in on this pull request. Can you confirm this is still a pending request for IX?

**Comment by pycnvr** [comment]
Yes.  Thanks

**Review by ix-certification — APPROVED** [review]
Please add examples for bid request/response and test configs in DOCUMENTATION.md
Approving .

**Comment by pycnvr** [comment]
Hi @ix-certification 

When will this be moved to production?  Thanks?

**Pull request merged**
