### PR TITLE
Add concert bid adapter

### PR DESCRIPTION
**Pull request by andrew-a-dev**
## Type of Change
- [x] New adapter
- [ ] Feature Update
- [ ] Bug Fix
- [ ] Code Refactor
- [ ] Other

## Description of Change

New IX adapter, for Concert ad network.

### CODE REVIEW

**Comment by ix-certification** [comment]
Hello, 
Can you please file a JIRA ticket using our Service Desk to get your PR prioritized and reviewed. Currently, we do not see any HTP JIRA ticket on our board filed, from your end. 

Thanks.!

**Comment by jplhomer** [comment]
This is ready to be reviewed!

**Comment by ix-certification** [comment]
If this is no more a work in progress, please remove the draft status

**Comment by andrew-a-dev** [comment]
> If this is no more a work in progress, please remove the draft status

Done, thank you. (Sorry about not having done that earlier.)

**Comment by ix-certification** [comment]
Hi andrew-a-dev,

Looks like your feature branch is 29 commits behind `indexexchange:master`. Would you be able to sync your branch with the latest changes from master?

**Comment by ix-certification** [comment]
Also, it looks like this pull request is based on the canary branch. Would you be able to make a new PR with your changes based on master?

**Comment by andrew-a-dev** [comment]
@ix-certification Thank you for those pointers! (I didn't realised we'd pulled in unrelated changes when we tried to revert from `canary` to `master`.) Hopefully, this has all been sorted out now. (All I see in the diff are the 4 commits for our new adapter.) 

I've force-pushed a "corrected" version of our branch to our repo, so I think this PR now reflects the correct state of affairs, but if you'd like me to open a wholly new PR, let me know, and I can do that too. Thanks!

**Comment by lksharma** [comment]
This looks good. Thanks, Andrew!

**Comment by lksharma** [comment]
Hi Andrew, 

I noticed that only post requests sent to `https://bids.concert.io/bids/ix` return with a valid response vs ones sent to `http://bids.concert.io/bids/ix` is this the expected?

**Pull request merged**
