### PR TITLE
HTP-131 Consumable: CCPA/GDPR Consent Support

### PR DESCRIPTION
**Pull request by djcsdy**
## Type of Change
- [ ] New adapter
- [x] Feature Update
- [ ] Bug Fix
- [ ] Code Refactor
- [ ] Other

## Description of Change
 * Import consumable adapter from external repository.

It looks like all the other adapters are gradually moving into the ix-library-adapters repository, so I moved the Consumable adapter from its existing separate repository. I’m not sure if this was the right thing to do. The original adapter was at https://github.com/indexexchange/consumable-adapter. Let me know if I should raise a PR against the original adapter instead.

 * Add support for CCPA and GDPR consent information.

This change is the main purpose of this update.

 * Add missing parameters to bid request.

Minor changes to bring the Index Exchange adapter in line with other adapters. This should not make any difference to bids at the moment, but might matter in future.

 * Improve documentation

Additional minor corrections to the existing documentation.

### CODE REVIEW

**Review by ix-certification — APPROVED** [review]

**Comment by cd0n0van** [comment]
Hi @djcsdy - IX is currently running this update in our canary branch but we are not able to confirm if your CCPA update is working as expected, as calls to your adapter have not returned any demand during canary testing. Can you please let IX know how you'd like to proceed? Feel free to DM me with questions or concerns. Thanks!

**Comment by djcsdy** [comment]
@cd0n0van Thanks for your help. It looks like we need to set up some demand for testing. That's not my area of expertise but I'm told @jgrimes will be able to help next week. cc @naffis.

**Comment by cd0n0van** [comment]
Hi @djcsdy @jgrimes @naffis - IX still has this update pending in our canary branch. Would you like to proceed with pushing it to main, or are there additional tests you're looking to run? Please let us know. Thank you!

**Comment by naffis** [comment]
Please push to main. Thank you.

**Pull request merged**
