### PR TITLE
Rubicon Adapter: Add CCPA and schain support

### PR DESCRIPTION
**Pull request by idettman**
## Type of Change

- [X] Feature Update

## Description of Change

Add support for CCPA and schain

### CODE REVIEW

**Comment by ix-certification** [comment]
There are some issues with the PR submitted. Feedback has been posted on the HTP ticket but our feedback has not been addressed yet by Rubicon. This ticket is blocked.

**Comment by cd0n0van** [comment]
Hi @harpere and @idettman - we've observed an issue with the CCPA update in canary testing. We are seeing the following values returned: status: "error", reason: "internal-error", error_code: "18". Can you please confirm if this is related to the update?

**Comment by cd0n0van** [comment]
Hi @idettman and @harpere - wanted to check in on this update before our deployment freeze. Would you like IX to proceed with promoting this change to our master branch? Feel free to DM me with any questions or concerns.

**Comment by cd0n0van** [comment]
Hi @idettman & @harpere - IX currently still has this code in our canary branch. Would you like us to go ahead and promote the change, observing the aforementioned errors, or are you looking to submit a new PR? Let me know if there's any additional information IX can provide to aid in troubleshooting!

**Pull request merged**
